version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace
    command: /bin/bash -c "while sleep 1000; do :; done"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      minio-1:
        condition: service_healthy
      minio-2:
        condition: service_healthy
      postgres:
        condition: service_healthy
      hive-metastore-1:
        condition: service_healthy
      hive-metastore-2:
        condition: service_healthy

  minio-1:
    image: bitnami/minio:2024.6.22
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: minio server /bitnami/minio/data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data-1:/bitnami/minio/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 20s
      retries: 30

  minio-setup-1:
    image: bitnami/minio-client:2024.1.18
    depends_on:
      minio-1:
        condition: service_healthy
    volumes:
      - ./minio/setup-minio-1.sh:/opt/bitnami/minio-client/setup-minio-1.sh
    entrypoint: /bin/bash /opt/bitnami/minio-client/setup-minio-1.sh

  minio-2:
    image: bitnami/minio:2024.6.22
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: minio server /bitnami/minio/data --console-address ":9001"
    ports:
      - "9002:9000"
      - "9003:9001"
    volumes:
      - minio-data-2:/bitnami/minio/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 5s
      timeout: 20s
      retries: 30

  minio-setup-2:
    image: bitnami/minio-client:2024.1.18
    depends_on:
      minio-2:
        condition: service_healthy
    volumes:
      - ./minio/setup-minio-2.sh:/opt/bitnami/minio-client/setup-minio-2.sh
    entrypoint: /bin/bash /opt/bitnami/minio-client/setup-minio-2.sh

  postgres:
    image: postgres:15.0-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init-multiple-db.sql:/docker-entrypoint-initdb.d/init-multiple-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d hive_metastore"]
      interval: 5s
      timeout: 10s
      retries: 30

  hive-metastore-1:
    build:
      context: ./hive-metastore
      dockerfile: ./metastore-1.Dockerfile
      args:
        CI_JOB_TOKEN: ${CI_JOB_TOKEN}
    environment:
      - HADOOP_VERSION=3.2.0
      - METASTORE_VERSION=3.1.3
      - HIVE_HOME=/opt/hive-metastore
      - HADOOP_HOME=/opt/hadoop-3.2.0
    ports:
      - "9083:9083"
    depends_on:
      postgres:
        condition: service_healthy
      minio-setup-1:
        condition: service_started
    healthcheck:
      test: [ "CMD-SHELL", "netstat -ln | grep 9083" ]
      interval: 5s
      timeout: 10s
      retries: 30

  hive-metastore-2:
    build:
      context: ./hive-metastore
      dockerfile: ./metastore-2.Dockerfile
      args:
        CI_JOB_TOKEN: ${CI_JOB_TOKEN}
    environment:
      - HADOOP_VERSION=3.2.0
      - METASTORE_VERSION=3.1.3
      - HIVE_HOME=/opt/hive-metastore
      - HADOOP_HOME=/opt/hadoop-3.2.0
    ports:
      - "9084:9083"
    depends_on:
      postgres:
        condition: service_healthy
      minio-setup-2:
        condition: service_started
    healthcheck:
      test: [ "CMD-SHELL", "netstat -ln | grep 9083" ]
      interval: 5s
      timeout: 10s
      retries: 30

volumes:
  minio-data-1:
  minio-data-2:
  postgres-data:
